@startuml

title Delivery pipeline

actor "Delivery Team" as team
participant VCS
participant "Build & Test" as build
participant "Automated acceptance tests" as accTests
participant "User acceptance tests" as userTests
participant Release

note over team, accTests #lightBlue: Advocated by CI
note over team, Release #skyBlue: Advocated by CD

team -> VCS: Push /\nCheck in
activate team
activate VCS
VCS -> build: Trigger
deactivate VCS
activate build #red
build --> team: Feedback
deactivate build
deactivate team

... Next try ...

team -> VCS: Push /\nCheck in
activate team
activate VCS
VCS -> build: Trigger
deactivate VCS
activate build #green
build --> team: Feedback
build -> accTests: Trigger
deactivate build
activate accTests #red
accTests --> team: Feedback
deactivate accTests
deactivate team

... Next try ...

team -> VCS: Push /\nCheck in
activate team
activate VCS
VCS -> build: Trigger
deactivate VCS
activate build #green
build --> team: Feedback
build -> accTests: Trigger
deactivate build
activate accTests #green
accTests --> team: Feedback
deactivate team
accTests -> userTests: Trigger with approval
deactivate accTests
activate userTests #green
userTests --> team: Feedback
userTests -> Release: Trigger with approval
deactivate userTests
activate Release #green
Release --> team: Feedback
deactivate Release

hide footbox

@enduml
